"""Единый контракт длины итогового Telegram TOP-3 поста."""


TELEGRAM_PHOTO_CAPTION_MAX_LENGTH = 1024

POST_LENGTH_SAFETY_MARGIN = 24

MAXIMUM_POST_LENGTH = (
    TELEGRAM_PHOTO_CAPTION_MAX_LENGTH
    - POST_LENGTH_SAFETY_MARGIN
)