"""Единый контракт длины итогового Telegram TOP-3 поста."""


TELEGRAM_PHOTO_CAPTION_MAX_LENGTH = 1024

POST_LENGTH_SAFETY_MARGIN = 24

MAXIMUM_POST_LENGTH = (
    TELEGRAM_PHOTO_CAPTION_MAX_LENGTH
    - POST_LENGTH_SAFETY_MARGIN
)

TARGET_POST_LENGTH_MIN = 850
TARGET_POST_LENGTH_MAX = 950

TARGET_HEADLINE_LENGTH_MIN = 45
TARGET_HEADLINE_LENGTH_MAX = 65
MAXIMUM_HEADLINE_LENGTH = 70

TARGET_BODY_LENGTH_MIN = 190
TARGET_BODY_LENGTH_MAX = 205
MAXIMUM_BODY_LENGTH = 210